src/app/events/[slug]/hero.tsx

This is a proposition to reduce the opacity of the hero image to make it more coherent with the graphical chart.

change the opacity of the hero image

---

src/app/events/[slug]/header.tsx
src/app/events/[slug]/hero.tsx
src/content/event/2024-06-07-rouen.mdx
src/content/event/2024-06-07-rouen/about.tsx

Add the link to the ticketing in the event of Rouen, disable cfp when tickets and add cfp button in the about section :

Add the link to buy tickets

---

src/app/(homepage)/banner.tsx
src/app/(homepage)/events.tsx
src/app/(homepage)/hero.tsx
src/lib/server.ts
src/lib/utils.ts

In the hero section : a card is display when tickets are available

Add a card on the Hero to get ticket

---

src/app/events/[slug]/hero.tsx
src/app/events/[slug]/page.tsx
src/app/events/[slug]/sponsors.tsx
src/app/events/[slug]/sponsorship.tsx
src/content/collections.ts
src/content/event/2024-06-07-rouen.mdx

We want to display the prospectus until a date. I put the date in the scheme and update the condition to not display the prospectus after the end date.

Add an endDate for the prospectus

---

src/app/events/[slug]/hero.tsx
src/components/ui/button.tsx

Change the logic to display the buttons on the hero of the event

Change the logic for the buttons on events

---

package-lock.json
package.json
src/app/events/[slug]/faq.tsx
src/app/events/[slug]/page.tsx
src/components/ui/accordion.tsx
src/content/collections.ts
src/content/event/2024-06-07-rouen.mdx

We want an Faq section : the questions are in the mdx of the event so we can adapt the questions and the answer depending on the event.

Add faq section

---

src/app/events/[slug]/page.tsx

I added the open graph url on the event page but I don't know how to fix for the code of conduct

Fix : Open graph and canonical url

---

src/app/events/[slug]/page.tsx
src/app/events/[slug]/schedule.tsx

Coming soon version of the schedule but I made it to add a condition to display the "schedule" or the real one when available (for each event)

Schedule coming soon 

---

package-lock.json
package.json
src/app/(homepage)/banner.tsx
src/app/(homepage)/events.tsx
src/app/(homepage)/hero.tsx
src/app/(homepage)/page.tsx
src/app/globals.css

Make the banner fix and add a "learn more" button on hero to go to the event page.

Upgrade the homepage

---

package-lock.json
package.json
src/app/events/[slug]/page.tsx
src/content/collections.ts
src/content/event/2024-06-07-rouen.mdx

Add all the facultative fields asked by schema.org on the event schema

Add the missing fields on the schema for structured data

---

src/content/event/2024-06-07-rouen.mdx

The speaker mdx already exist, I just forgot to put his name on the Rouen event I think.

Add the missing speaker : Yann Jacquot

---

src/app/(homepage)/partners.tsx
src/app/events/[slug]/faq.tsx
src/app/events/[slug]/page.tsx
src/app/events/[slug]/sponsors.tsx

Il followed the mockups : 
I just changed the gap between 2 sponsors on mobile screen because it was wierd.

Change style for the sponsor section, adapte the partners and faq sections

---

package-lock.json
package.json
src/app/events/[slug]/header.tsx
src/app/events/[slug]/page.tsx
src/app/events/[slug]/schedule.tsx
src/app/events/[slug]/schedule/page.tsx
src/content/collections.ts
src/content/event/2024-06-07-rouen.mdx
src/content/talk/chapter-lead-retour-dxp-apres-2-ans-de-mise-en-place-chez-bforbank.mdx
src/content/talk/comment-on-a-decoupe-notre-legacy.mdx
src/content/talk/eco-conception-contrainte-ou-opportunite.mdx
src/content/talk/et-si-on-reprenait-le-controle-de-notre-vie-privee-en-ligne.mdx
src/content/talk/how-to-make-your-open-source-project-popular.mdx
src/content/talk/il-est-difficile-de-faire-simple.mdx
src/content/talk/la-performance-web-le-cas-de-lafrique.mdx
src/content/talk/le-pouvoir-des-choix-devenez-le-heros-de-votre-carriere.mdx
src/content/talk/maintaining-an-open-source-library-for-Next-js-feedback-and-tips.mdx
src/content/talk/microservices-maxi-supplice.mdx
src/content/talk/migrer-de-drupal-7-a-drupal-10.mdx
src/content/talk/tropical-software-developper-un-logiciel-pour-un-ministere-dasie-du-sud-est.mdx
src/content/talk/une-ode-a-la-programmation-tacite.mdx
src/content/talk/ux-design-through-the-eyes-of-an-architect.mdx
src/lib/utils.ts

Adapt the mdxs, the schema and create the schedule section and page

Create schedule section and page 

---

src/content/sponsor/attineos.mdx

Update the info for Attineos

---

package.json
src/content/event/2024-06-07-rouen.mdx

I added 5 minutes on morning and afternoon breaks and 15 minutes on lunch break

Update the schedule : keynote, add time on breaks and move talks

---

src/app/(homepage)/banner.tsx

I put the link around the entire banner not only the text

Fix : make the entire banner clickable not just the text

---

src/app/events/[slug]/schedule.tsx
src/app/events/[slug]/talks.tsx
src/app/events/[slug]/talks/[talk]/page.tsx
src/components/language-badge.tsx
src/components/ui/badge.tsx
src/content/collections.ts
src/content/talk/chapter-lead-retour-dxp-apres-2-ans-de-mise-en-place-chez-bforbank.mdx
src/content/talk/comment-on-a-decoupe-notre-legacy.mdx
src/content/talk/et-si-on-reprenait-le-controle-de-notre-vie-privee-en-ligne.mdx
src/content/talk/how-to-make-your-open-source-project-popular.mdx
src/content/talk/il-est-difficile-de-faire-simple.mdx
src/content/talk/la-performance-web-le-cas-de-lafrique.mdx
src/content/talk/le-pouvoir-des-choix-devenez-le-heros-de-votre-carriere.mdx
src/content/talk/maintaining-an-open-source-library-for-Next-js-feedback-and-tips.mdx
src/content/talk/microservices-maxi-supplice.mdx
src/content/talk/migrer-de-drupal-7-a-drupal-10.mdx
src/content/talk/tropical-software-developper-un-logiciel-pour-un-ministere-dasie-du-sud-est.mdx
src/content/talk/une-ode-a-la-programmation-tacite.mdx
src/content/talk/ux-design-through-the-eyes-of-an-architect.mdx

The goal is to add the language flag for each talk : on the schedule, on the talk section and on each talk page.

Feat: add talks language

---

src/app/layout.tsx

[Capture vidéo du 27-05-2024 10:22:55.webm](https://github.com/Fork-It-Community/forkit.community/assets/77801791/2044177b-6d92-4a01-9550-03fbf8d6803a)

feat : add scroll smooth on layout

---

src/content/speaker/francois-best.mdx

I tend to keep it lowercase everywhere.

chore: Update `nuqs` case in speaker profile

---

src/content/event/2024-06-07-rouen.mdx

feat: add new questions on the faq

---

src/content/event/2024-06-07-rouen/informations.mdx

feat: add the links to the parkings with google map and add Rudy's secret parking

---

src/app/events/[slug]/talks/[talk]/page.tsx
src/content/speaker/alexis-stefanski.mdx
src/content/speaker/antoine-mazure.mdx
src/content/speaker/arnaud-mary.mdx
src/content/speaker/ayoub-alouane.mdx
src/content/speaker/frederic-bisson.mdx
src/content/speaker/magali-de-labareyre.mdx
src/content/speaker/olivier-huber.mdx
src/content/speaker/sebastien-ferrer.mdx
src/content/speaker/xavier-van-de-woestyne.mdx
src/content/speaker/yann-jacquot.mdx

Add speaker's bio on each talk page

feat: add speakers bio

---

src/components/favorite-button.tsx

Add aria label on the favorite button for accessibility

fix: add the aria label on the favorite button

---

package.json
pnpm-lock.yaml
src/components/ui/button.tsx

Use shadcn button and adapt it with the fork it style.

Feat : Create button component

---

src/content/meetup/2024-09-24-tunis/about.tsx

Add photograph copyright on Tunis meetup image

feat : add photograph copyright

---

src/content/meetup/2024-09-24-tunis.mdx
src/content/talk/deployment-as-a-service.mdx

Add Idriss Neumann talk on the meetup page

feat : add idriss talk on tunis meetup

---

src/app/meetups/[slug]/schedule.tsx
src/content/meetup/2024-09-24-tunis.mdx

Add schedule on website, there is no start time for the talks and the break to be more flexible, just the reception time

Feat : add schedule

---

src/content/config.ts
src/content/people/people.ts
src/content/speakers/speaker.ts

* **I decalred the type of this collection as data in order to use [reference](https://docs.astro.build/en/guides/content-collections/#defining-collection-references)**
- **`name`**: The name of the person.
- **`imageUrl`**: URL to the person's image.
- **`job`**: The person's job or professional title.
- **`socials`**: An array of social media links related to the person.
- **`type`**: The type of social platform (e.g., Twitter, LinkedIn).
- **`href`**: The URL to the social profile.
- **`company`**: Information about the person's current company.
- **`title`**: The company's name.
- **`href`**: The company's website URL.
- **`companyHref`**: The URL to the company's website, if not included in the `company` object.

Feat : add people collection

---

src/components/demo.tsx
src/components/explore-the-community.tsx
src/content/components/button.mdx
src/content/components/components.ts
src/content/components/explore-community.mdx
src/content/config.ts
src/layouts/BrandingLayout.astro
src/pages/branding/components/[slug]/index.astro
src/pages/branding/index.astro

Our goal is to create a "stories" collection of all the components in this project, in order to generate static documentation for each component.
PS: Whenever you add a component to the components collection, please write it below. 😊

Feat setup storybook like

---

src/pages/404.astro

 not found page

---

src/components/ui/badge.tsx
src/components/ui/tag.tsx
src/content/components/badge.mdx

Feat: component tag

---

src/app/(homepage)/hero.tsx
src/app/(homepage)/upcoming-events.tsx
src/app/(homepage)/upcoming-meetups.tsx
src/lib/utils.ts

feat : add logic to button to show past events or next events

---

src/content/blogs/blogs.ts
src/content/config.ts
src/pages/blogs/[slug]/index.astro
src/pages/blogs/index.astro

- **`title`**: `string`  
The title of the blog post.
- **`description`**: `string` (optional)  
A brief summary or preview text for the blog post.
- **`BlogImage`**: `object` (optional)  
An optional image object with:
- **`src`**: `string`  
The URL of the image.
- **`alt`**: `string`  
Alternative text for the image.
- **`author`**: `object`  
Details about the author, including:
- **`name`**: `string`  
The name of the author.
- **`Linkedin`**: `string` (optional)  
The author's LinkedIn profile URL.
- **`date`**: `date`  
The publication date of the blog post. 
- **`readingTime`**: `number` (optional)  
The estimated reading time of the blog post, in minutes.
- **`tags`**: `array` of `string` (optional)  
Tags related to the blog post.
- **`isTopPost`**: `boolean`  
A flag indicating …

 prepare blog section

---

src/app/meetups/[slug]/hero.tsx
src/app/meetups/[slug]/talks/[talk]/page.tsx
src/content/meetup/2024-10-22-kuala-lumpur.mdx
src/content/meetup/2024-11-05-bangkok.mdx
src/content/speaker/kan-pawarisson.mdx

feat : small fixes and changes

---

src/components/timeline/index.tsx

Based on the component I found, I made some adjustments to align the timeline with the Figma design: [shadcn-timeline](https://github.com/timDeHof/shadcn-timeline)
* currently shadcn has no timeline component but it will have in the future according to this[ issue and talks](https://github.com/shadcn-ui/ui/issues/2141) 
* I couldn’t use a 0.5px width for the dashed line because, when tested on Firefox, the  line was not displayed.
*  **i changed `TimelineConnector` style in order to reduce  the opacity for the last dashed line , please check if what i did is correct or can be changed** 
```jsx
---
import { TimelineItem } from "@/components/timeline";
import { TimelineHeader } from "@/components/timeline";
import { TimelineIcon } from "@/components/timeline";
import { TimelineContent } …
```

Timeline component

---

src/components/EventCard/index.astro
src/pages/events/index.astro

feat: improve events listing for upcoming events

---

src/pages/events/[id]/pages/[subpageId]/index.astro
src/pages/events/[id]/schedule/index.astro

feat : add meta description for schedule and supbages

---

src/components/Schedule/TimeAndDuration.astro
src/components/Schedule/index.astro
src/pages/events/[id]/talks/[talkId]/index.astro

feat : add time and room to talk page

---

src/components/EventCard/index.astro
src/content/events/2024-belgium-ottignies-louvain-la-neuve/index.mdx
src/content/events/2024-france-rouen/index.mdx
src/content/events/2024-malaisia-kuala-lumpur/index.mdx
src/content/events/2024-morocco-casablanca/index.mdx
src/content/events/2024-thailand-bangkok/index.mdx
src/content/events/2024-tunisia-tunis/index.mdx
src/content/events/2024-vietnam-da-nang/index.mdx
src/content/events/2024-vietnam-hanoi/index.mdx
src/content/events/2025-thailand-bangkok/index.mdx
src/content/events/2025-tunisia-nabeul/index.mdx
src/layouts/EventLayout.astro
src/layouts/EventSubPageLayout.astro
src/pages/events/[id]/dynamic-images/_og-image.tsx
src/pages/events/[id]/dynamic-images/_save-the-date.tsx
src/pages/events/[id]/dynamic-images/_tickets-available.tsx
src/pages/events/[id]/index.astro
src/pages/events/[id]/talks/[talkId]/dynamic-images/_og-image.tsx
src/pages/events/[id]/talks/[talkId]/dynamic-images/_square.tsx
src/pages/index.astro
src/schemas/events.ts

fix : rename event image content from src to media

---

src/components/EventCTA/index.tsx
src/lib/events.ts
src/pages/events/[id]/index.astro

Handle primary, secondary and tertiary button on event

feat: better event cta handle

---

src/components/PersonCard/index.astro
src/components/Schedule/CardBreak.astro
src/components/Schedule/CardConference.astro
src/components/Schedule/CardInfo.astro
src/components/Schedule/ComingSoon.astro
src/components/Schedule/index.astro
src/content/events/2024-belgium-ottignies-louvain-la-neuve/index.mdx
src/content/events/2024-france-rouen/index.mdx
src/content/events/2024-malaisia-kuala-lumpur/index.mdx
src/content/events/2024-morocco-casablanca/index.mdx
src/content/events/2024-thailand-bangkok/index.mdx
src/content/events/2024-tunisia-tunis/index.mdx
src/content/events/2024-vietnam-da-nang/index.mdx
src/content/events/2024-vietnam-hanoi/index.mdx
src/content/events/2025-thailand-bangkok/index.mdx
src/content/events/2025-tunisia-nabeul/index.mdx
src/content/events/2025-tunisia-tunis/index.mdx
src/pages/events/[id]/assets/_utils.ts
src/pages/events/[id]/index.astro
src/pages/events/[id]/schedule/index.astro
src/pages/events/[id]/talks/[talkId]/index.astro
src/schemas/events.ts

Closes #234 
The goal is to present the potential schedule and the numbers instead of coming soon

Feat : rework coming soon schedule

---

src/pages/code-of-conduct.astro

**Changes**
- Added the proper slot attribute to the SEO component on the Code of Conduct page
Close: #257

fix: add seo slot to code of conduct page

---

src/content/events/2025-tunisia-tunis/pages/weekend.mdx

fixing feedbacks here: https://github.com/Fork-It-Community/forkit.community/pull/261

fix feedbacks for weekend's guide for event tunis 2025

---

src/components/JoinNewsletter/index.astro
src/components/ui/button.tsx
src/pages/index.astro

feat: add newsletter on homepage

---

src/content/podcasts/fork-it-community-tech-podcast-fr/episodes/1/index.mdx
src/content/podcasts/fork-it-community-tech-podcast-fr/episodes/2/index.mdx
src/content/podcasts/fork-it-community-tech-podcast-fr/episodes/3/index.mdx

added YouTube links to podcasts

feat: add link to podcasts

---

src/pages/events/index.astro
src/pages/events/locations/[countryId]/index.astro

FIX : Sort country and city

---

package.json
pnpm-lock.yaml
scripts/generate-routes.ts
src/content/events/2025-tunisia-tunis/index.mdx
src/lib/events.ts
src/pages/events/[id].html.md/index.ts
src/pages/events/[id]/index.html.md.ts
src/pages/llms.txt.ts
src/pages/people/[id].html.md/index.ts
src/pages/podcasts/[id]/episodes/[episodes].html.md/index.ts
src/routes.gen.ts

- Go to https://forkit-community-git-feat-llms-txt-bearstudio.vercel.app/llms.txt for the entry point

feat: add llms.txt and first markdown file as a base structure

---

src/content/events/2025-malaysia-kuala-lumpur/index.mdx

add the ticketing link to the event's content and the end date for the cfp

feat: add ticketing information for Kuala Lumpur event and end cfp

---

src/components/Faq/index.tsx
src/content/events/2025-malaysia-kuala-lumpur/index.mdx

Added the FAQ section for the Kuala Lumpur event and updated the answers to support HTML elements, allowing inclusion of clickable links.

Add Kual Lumpur's FAQ

---

src/components/OrganizersList/index.astro
src/content/cities/tunis/index.mdx
src/content/countries/france/index.mdx
src/content/countries/thailand/index.mdx
src/content/countries/tunisia/index.mdx
src/lib/people.ts
src/pages/events/locations/[countryId]/[cityId]/index.astro
src/pages/events/locations/[countryId]/index.astro
src/routes.gen.ts
src/schemas/city.ts
src/schemas/country.ts

closes #356 
closes https://github.com/Fork-It-Community/forkit.community/pull/361 (reused work from @antoinekm)

feat: add organizers on locations

---

src/components/EventsList/index.astro
src/components/StayTuned/index.astro
src/pages/events/[id]/index.astro
src/pages/events/locations/[countryId]/[cityId]/index.astro
src/pages/events/locations/[countryId]/index.astro

feat: extract component and add it to country page
